meta:
  name: 'DKBans English'
  module: 'DKBans'
  language:
    name: 'English'
    localizedName: 'English'
    code: 'en'
messages:
  dkbans.prefix: '&8» &4DKBans &8|&f'
  dkbans.prefix.network: '&8» &4DKNetwork &8|&f'
  dkbans.prefix.report: '&8» &6DKReport &8|&f'
  dkbans.prefix.teamchat: '&8» &eTeamChat &8|&f'
  dkbans.prefix.chat: '&8» &eChat &8|&f'

  dkbans.error.internal: '{prefix} &cAn internal server error occurred, please contact a network administrator"'
  dkbans.error.invalid.DurationFormat: '{prefix} &e{duration} &cis not a valid duration'
  dkbans.error.invalid.number: '{prefix} &e{number} &cis not a valid number'
  dkbans.error.onlyPlayer: '{prefix} &cThis command can only be executed as a player'
  dkbans.error.onlyConsole: '{prefix} &cThis command can only be executed from console'
  dkbans.error.noPermissions: '{prefix} &cYou are not allowed to execute this command'

  dkbans.player.notFound: '{prefix} &cThe player &e{name} &cwas not found'
  dkbans.player.notOnline: '{prefix} &cThe player &e{player.displayName} &cis not online'
  dkbans.player.notSelf: '{prefix} &cYou can''t interact with your self'
  dkbans.player.hasBypass: '{prefix} &cYou are not allowed to punish this player'

  dkbans.player.staff.status.now: '{prefix} &7You are {statusFormatted}'
  dkbans.player.staff.status.already: '{prefix} &7You are already {statusFormatted}'
  dkbans.player.staff.status.change: '{prefix} &7You have {statusFormatted}'
  dkbans.player.staff.status.not: '{prefix} &7You are not {statusFormatted}'
  dkbans.player.staff.status.login: '&alogged in'
  dkbans.player.staff.status.logout: '&clogged out'

  dkbans.server.notFound: '${dkbans.prefix.network} &cThe server &e{name} &c was not found'
  dkbans.server.alreadyConnected: '${dkbans.prefix.network} &cYou are already connected to this server'
  dkbans.server.connecting: '${dkbans.prefix.network} &7Connecting to {server.name}...'

  dkbans.ping.self: '${dkbans.prefix.network} &7Your ping is &e{ping}&7ms'
  dkbans.ping.other: '${dkbans.prefix.network} &7The ping of &e{player.displayName} &7is &a{ping}&7ms'

  dkbans.onlineTime.self: '${dkbans.prefix.network} &7Your online time is &e{online-time-formatted-short}&cms'
  dkbans.onlineTime.other: '${dkbans.prefix.network} &7The ping of &e{player.displayName} &7is &e{online-time-formatted-short}&cms'

  dkbans.chat.filter.toFast: '${dkbans.prefix.chat} &cYou are chatting to fast.'
  dkbans.chat.filter.repeat: '${dkbans.prefix.chat} &cYou are repeating yourself.'

  dkbans.filter.blocked.command: '${dkbans.prefix.chat} &fUnknown command. Type "/help" for help.'
  dkbans.filter.blocked.insulting: '${dkbans.prefix.chat} &cPlease pay attention to your choice of words.'
  dkbans.filter.blocked.advertising: '${dkbans.prefix.chat} &fUnknown command. Type "/help" for help.'
  dkbans.filter.blocked.name: '&e&lexample.net
  &7
  &cYour nickname is not allowed on this server
  &7
  &aIf you change you name, you can join :D'

  dkbans.punish.template.noPermission: '{prefix} &cYou are not allowed to use this reason'
  dkbans.punish.template.list: '{prefix} &7Available reasons&8:
  @for("template" in {templates},${dkbans.punish.template.list.loop},"\n")'
  dkbans.punish.template.list.loop: ' &8- &c{template.inGroupId} &8| &4{template.displayName} &8» &4&l{template.firstType.name}'

  dkbans.punish.ban.message.permanently: '&e&lexample.net
  &e
  &cYou are &4&lpermanently banned &cfrom this network
  &3Reason&8: &4&l{ban.reason}
  &3BanID&8: &7{ban.id}
  &e
  &aYou can make a unban request at &eforum.example.net.'
  dkbans.punish.ban.message.temporary: '&e&lexample.net&r
  &e
  &cYou are &e&l{ban.durationFormatted} &cbanned from this network
  &3Reason&8: &4&l{ban.reason}
  &3BanID&8: &7{ban.id}
  &e
  &3Remaining time&8: &e{ban.remainingFormatted}
  &e
  &aYou can make a unban request at &eforum.example.net'
  dkbans.punish.ban.notify: '${dkbans.prefix} &9{player.displayName} &7has been &cbanned &7by &8{ban.staff.displayName} &7for &4{ban.reason}&7'

  dkbans.punish.mute.message.permanently: '&5
  ${dkbans.prefix} &cYou are &4&lPermanently &cbanned from the chat
  &8» &3Reason&8: &4&l{mute.reason}
  &8» &3BanID&8: &7{mute.id}
  &7'
  dkbans.punish.mute.message.temporary: '&5
  ${dkbans.prefix} &cYou are &e&l{mute.durationFormatted} &cbanned from the chat
  &8» &3Reason&8: &4&l{mute.reason}
  &8» &3BanID&8: &7{mute.id}
  &e
  &8» &3Remaining time&8: &e{mute.remainingFormatted}
  &7'
  dkbans.punish.mute.notify: '${dkbans.prefix} &9{player.displayName} &7has been &9muted &7by &8{mute.staff.displayName} &7for &4{mute.reason}&7'

  dkbans.punish.kick.message: '&e&lexample.net&r
  &e
  &cYou were kicked from the network
  &3Reason&8: &4&l{kick.reason}'

  dkbans.punish.kick.notify: '${dkbans.prefix} &9{player.displayName} &7has been &ekicked &7by &8{kick.staff.displayName} &7for &4{kick.reason}&7'

  dkbans.punish.warn.message.chat: '&5
  ${dkbans.prefix} &cYou have been warned
  &8» &3Reason&8: &4&l{warn.reason}
  &8» &3WarnID&8: &7{warn.id}
  &7'
  dkbans.punish.warn.notify: '${dkbans.prefix} &9{player.displayName} &7has been &6warned s&7by &8{warn.staff.displayName} &7for &4{warn.reason}&7'


  dkbans.punish.success.ban: '${dkbans.prefix} &e{player.displayName} &7was banned'
  dkbans.punish.success.mute: '${dkbans.prefix} &e{player.displayName} &7was muted'
  dkbans.punish.success.kick: '${dkbans.prefix} &e{player.displayName} &7was kicked'
  dkbans.punish.success.warn: '${dkbans.prefix} &e{player.displayName} &7was warned'

  dkbans.report.countInfo: '${dkbans.prefix.report} &7Open reports&8: &e{openReports}'

  dkbans.punish.list.ban: '${dkbans.prefix} &6Banned players &8| &7{page} @for("punish" in {punishments},${dkbans.punish.list.loop},"\n","\n")'
  dkbans.punish.list.mute: '${dkbans.prefix} &6Muted players &8| &7{page} @for("punish" in {punishments},${dkbans.punish.list.loop},"\n","\n")'
  dkbans.punish.list.loop: ' &8- &e{punish.history.player.displayName} &8- &7{punish.reason}'

  dkbans.punish.already.banned: '${dkbans.prefix} &e{player.displayName} &cis already banned'
  dkbans.punish.already.muted: '${dkbans.prefix} &e{player.displayName} &cis already muted'
  dkbans.punish.override: '${dkbans.prefix} &7Do you want override it? !["&8[&7Click&8]"]("run://{command}")'


  dkbans.punish.not.banned: '${dkbans.prefix} &e{player.displayName} &cis not banned'
  dkbans.punish.not.muted: '${dkbans.prefix} &e{player.displayName} &cis not muted'

  dkbans.unpunish.help: '${dkbans.prefix} &cUsage&8: &7/{command} <player> [Reason]'
  dkbans.unpunish.success.ban: '${dkbans.prefix} &e{player.displayName} &7was unbanned'
  dkbans.unpunish.success.mute: '${dkbans.prefix} &e{player.displayName} &7was unmuted'


  dkbans.command.punish.help.temporary: '${dkbans.prefix} &7/{command} <player> <duration> <reason>'
  dkbans.command.punish.help.permanently: '${dkbans.prefix} &7/{command} <player> <reason>'
  dkbans.command.punish.help.oneTime: '${dkbans.prefix} &7/{command} <player> <reason>'

  dkbans.command.history.help: '${dkbans.prefix} &cUsage&8: &7/history <player>'
  dkbans.command.history.list: '${dkbans.prefix} &7History from &8{player.displayName} @for("entry" in {entries}",${dkbans.command.history.list.loop},"\n","\n")'
  dkbans.command.history.list.loop: '&8» &a{entry.punishmentType.color}{entry.punishmentType.name} &8| &7{entry.createdFormatted} - &7{entry.reason}'

  dkbans.command.resetHistory.help: '${dkbans.prefix} &7Reset history help
  &7/resethistory <player>
  &7/resethistory <player> <id>
  &7/resethistory last <amount>
  &7/resethistory last <duration>
  &7/resethistory by <staff>'
  dkbans.command.resetHistory.many: '${dkbans.prefix} &7The history from &8{player.displayName} &7was reset'
  dkbans.command.resetHistory.one: '${dkbans.prefix} &7The history entry &c{id} from {player.displayName} &7was reset'

  dkbans.teamchat.messageFormat: '${dkbans.prefix.teamchat}&8{sender.displayName} &8» &7{message}'

  dkbans.command.report.help: '${dkbans.prefix} &cUsage&8: &7/report <player> <Reason>'
  dkbans.command.report.template.notExist: '${dkbans.prefix.report} &cThe report template &e{name} &cdoes not exist'
  dkbans.command.report.already.reported: '${dkbans.prefix.report} &cYou have already &e{player.name} &creported'
  dkbans.command.report.reported: '${dkbans.prefix.report} &7You have reported &e{player.name} &7for &e{reason}'
  dkbans.command.report.listTemplates: '${dkbans.prefix.report} &6Available report templates
  @for("template" in {templates}, ${dkbans.command.report.listTemplates.loop},"\n")'
  dkbans.command.report.listTemplates.loop: ' &8- &c{template.inGroupId} &8| &e{template.displayName}'
  dkbans.command.report.take.usage: '${dkbans.prefix.report} &cUse /report take <name>'
  dkbans.report.notFound: '${dkbans.prefix.report} &cA report for &e{player.name} &cwas not found'
  dkbans.command.report.take: '${dkbans.prefix.report} &7You have took the report of &e{target.name}'
  dkbans.command.report.take.already: '${dkbans.prefix.report} &cThe report of &e{target.name} has been already taken'
  dkbans.command.report.accept.usage: '${dkbans.prefix.report} &cUse /report accept <name>'
  dkbans.command.report.accept.notWatching: '${dkbans.prefix.report} &cYou are not watching this player'
  dkbans.command.report.accept.listEntries: '${dkbans.prefix.report} &7Available reports&8: @for("entry" in {entries}, ${dkbans.command.report.listTemplates.loop},"\n","\n")'
  dkbans.command.report.accept.listEntries.loop: ' &8- ![{entry.template.displayName}]("run://{entry.punishmentCommand}")'
  dkbans.command.report.decline.usage: '${dkbans.prefix.report} &cUsage&8: /report decline <name>'
  dkbans.command.report.decline: '${dkbans.prefix.report} &cYou have declined the report of &e${target.displayName}'
  dkbans.command.report.list: '${dkbans.prefix.report} &7Open reports&8:
  @for("report" in {reports}, ${dkbans.command.report.list.loop},"\n")'
  dkbans.command.report.list.loop: ' &8- &e{report.player.displayName} &7Count&8: &e{report.count}'

  dkbans.command.report.notify: '![${dkbans.command.report.notify.text};${dkbans.command.report.notify.hover}]("run:///report take {player.name}")'
  dkbans.command.report.notify.text: '${dkbans.prefix.report} &e{player.displayName} &8&l>> &e{report.reason} &8[&7Click&8]'
  dkbans.command.report.notify.hover: '&8» &7Player&8: &c{player.displayName}
  &8» &7Reporter&8: &c{report.reporter.displayName}
  &8» &7Reason&8: &c{report.reason}
  &8» &7Server&8: &c{report.serverName}'

  dkbans.command.filter.help: '${dkbans.prefix.chat} &6Filter help
  &7/filter list [area]
  &7/filter add <area> <value> <operation>
  &7/filter remove <id>
  &7
  &8» &7Areas&8:
   &8- &eCHAT_ADVERTISING
   &8- &eCHAT_INSULT
   &8- &eCOMMAND
   &8- &eCOMMAND_MUTE
   &8- &ePLAYER_NAME

  &8» &7Operations&8:
   &8- &eEQUALS
   &8- &eCONTAINS
   &8- &eSTARTS_WITH
   &8- &eENDS_WITH
   &8- &eREGEX
  '
  dkbans.command.filter.affiliationArea.notFound: '${dkbans.prefix.chat} &cThe affiliation area &c{area} &cwas not found'
  dkbans.command.filter.operation.notFound: '${dkbans.prefix.chat} &cThe filter operation &c{operation} &cwas not found'
  dkbans.command.filter.notFound: '${dkbans.prefix.chat} &cThe filter &c{id} &cwas not found'
  dkbans.command.filter.list: '${dkbans.prefix.chat} &7Available filters&8: @for("filter" in {filters},${dkbans.command.filter.list.loop},"\n","\n")'
  dkbans.command.filter.list.loop: ' &8- &7{filter.affiliationArea} &8| &7{filter.id} &8- &7{filter.value} &8(&7{filter.operationName}&8)'
  dkbans.command.filter.created: '${dkbans.prefix.chat} &7The filter &e{filter.id} &8- &e{filter.value} &7for &e{filter.affiliationArea} &7was created'
  dkbans.command.filter.deleted: '${dkbans.prefix.chat} &7The filter &e{filter.id} &8- &e{filter.value} &7for &e{filter.affiliationArea} &7was deleted'

  dkbans.command.teamChat.help: '${dkbans.prefix.teamchat} &cUsage&8: &7/teamchat <login/logout/toggle/message>'
  dkbans.command.notify.help: '${dkbans.prefix.network} &cUsage&8: &7/notify <login/logout/toggle>'
  dkbans.command.kick.help: '${dkbans.prefix.dkbans} &cUsage&8: &7/kick <player> <reason>'
  dkbans.command.jumpto.help: '${dkbans.prefix.network} &cUsage&8: &7/jumpto <player>'

  dkbans.command.help: '${dkbans.prefix.network} &6Information
  &8» &e/hub &8| &7Connect to the Hub-Server
  &8» &e/report &8| &7Report a player
  &8» &e/friends &8| &7Manage your friends
  &7&8
  &8» &eTeamSpeak&8: &bts.example.net
  &8» &eForum&8: &bforum.example.net
  &8» &eShop&8: &bshop.example.net'

  dkbans.command.playerInfo.help: '${dkbans.prefix} &cUsage&8: &7/playerinfo <player>'
  dkbans.command.playerInfo.online: '${dkbans.prefix} &6Player Info
  &8» &7Name&8: &e{player.displayName} &8(&aOnline&8)
  &8» &7UniqueId&8: &e{player.uniqueId}
  &8» &7FirstLogin&8: &e{player.firstLogin}
  &8» &7Server&8: &e{player.server}
  &8» &7OnlineTime&8: &e{player.onlineTime}
  &8» &7Ip&8: &e{player.activeSession.HostName}
  &8» &7Country&8: &e{player.activeSession.country}
  &8» &7Region&8: &e{player.activeSession.region}'
  dkbans.command.playerInfo.offline: '${dkbans.prefix} &6Player Info
  &8» &7Name&8: &e{player.displayName} &8(&cOffline&8)
  &8» &7UniqueId&8: &e{player.uniqueId}
  &8» &7FirstLogin&8: &e{player.firstLogin}
  &8» &7LastLogin&8: &e{player.lastLogin}
  &8» &7OnlineTime&8: &e{player.onlineTime}
  &8» &7Ip&8: &e{player.activeSession.hostName}
  &8» &7Country&8: &e{player.activeSession.country}
  &8» &7Region&8: &e{player.activeSession.region}'


  dkbans.command.playerNotes.help: '${dkbans.prefix} &cUsage&8: &7/pnotes <list,add> '
  dkbans.command.playerNotes.list: '${dkbans.prefix} &cUsage&8: &7/pnotes
  @for("note" in {notes},{dkbans.command.playerNotes.list.loop},"\n","\n")'
  dkbans.command.playerNotes.list.loop: '&8» &e{note.formattedTime} &8- {note.creator.displayName}&8:
  &8> &7{note.message}'C
  dkbans.command.playerNotes.added: '&8» &a+ &e{note.formattedTime} &8- {note.creator.displayName}&8:
  &8> &7{note.message}'
  dkbans.command.chatLog.usage: '${dkbans.prefix.chat} &cInvalid usage of chatLog command&8:
  &7/chatlog player <name> [page]
  &7/chatlog server <name, id> [page]'
  dkbans.command.chatLog.list: '${dkbans.prefix.chat} &6ChatLog page {page}
  @for("entry" in {entries}, ${dkbans.command.chatLog.list.loop},"\n")'
  dkbans.command.chatLog.list.loop: '&8» {entry.player.displayName} &7on &e{entry.timeFormatted}&8: &f{entry.message}'
  dkbans.command.dkbans.help: '${dkbans.prefix} &cInvalid usage of &eDKBans &ccommand&8
  &8» &7/dkbans migrate <name> (Only executable from console)'
  dkbans.command.dkbans.template.import: '${dkbans.prefix} &7You have imported &e{count} &7template groups with an amount of &e{templateCount} &7templates'
  dkbans.command.joinme.notEnoughAmount: '${dkbans.prefix} &cYou can not send a joinme'
  dkbans.command.joinme.usage: '${dkbans.prefix} &cUsage&8: &7/joinme [playerId]'
  dkbans.command.joinme.notExists: '${dkbans.prefix} &cThis joinme does not exist'
  dkbans.command.joinme.line1: '&6'
  dkbans.command.joinme.line2: '&6'
  dkbans.command.joinme.line3: '&6'
  dkbans.command.joinme.line4: '&6'
  dkbans.command.joinme.line5: '  &e{player.displayName} &7is playing on &e{server}'
  dkbans.command.joinme.line6: '           &7Click to join'
  dkbans.command.joinme.line7: '&6'
  dkbans.command.joinme.line8: '&6'
  dkbans.command.joinme.line9: '&6'
  dkbans.command.joinme.line10: '&6'
