meta:
  name: 'DKBans English'
  module: 'DKBans'
  language:
    name: 'English'
    localizedName: 'English'
    code: 'en'
messages:
  dkbans.prefix: '&8» &4DKBans &8|&f'
  dkbans.prefix.network: '&8» &4DKNetwork &8|&f'
  dkbans.prefix.report: '&8» &6DKReport &8||&f'
  dkbans.prefix.teamchat: '&8» &eTeamChat &8|&f'
  dkbans.prefix.chat: '&8» &eChat &8|&f'

  dkbans.error.internal: '{prefix} &cAn internal server error occurred, please contact a network administrator"'
  dkbans.error.invalidDurationFormat: '{prefix} &e{duration} &cis not a valid duration"'
  dkbans.error.onlyPlayer: '{prefix} &cThis command can only be executed as a player"'

  dkbans.player.notFound: '{prefix} &cThe player &e{name} &cwas not found"'
  dkbans.player.notOnline: '{prefix} &cThe player &e{player.displayName} &cis not &aonline'
  dkbans.player.notSelf: '{prefix} &cYou can''t interact with your self'
  dkbans.player.hasBypass: '{prefix} &cYou are not allowed to punish this player'

  dkbans.player.staff.status.now: '{prefix} &7You are {status}'
  dkbans.player.staff.status.already: '{prefix} &7You are already {status}'
  dkbans.player.staff.status.change: '{prefix} &7You have [status]'
  dkbans.player.staff.status.not: '{prefix} &7You are not [status]'
  dkbans.player.staff.status.login: '&alogged in'
  dkbans.player.staff.status.logout: '&clogged out'

  dkbans.server.notFound: '${dkbans.prefix.network} &cThe server &e{name} &c was not found'
  dkbans.server.alreadyConnected: '${dkbans.prefix.network} &cYou are already connected to this server'
  dkbans.server.connecting: '${dkbans.prefix.network} &7Connecting to {server.name}...'

  ping.self: '${dkbans.prefix.network} &7Your ping is &e{ping}&cms'
  ping.other: '${dkbans.prefix.network} &7The ping of &e{player.displayName} &7is &a{ping}&cms'

  dkbans.punish.message.ban.permanently: '&e&lexample.net
  &e
  &cYou are &4&lpermanently banned &cfrom this network
  &3Reason&8: &4&l{ban.current.reason}
  &3BanID&8: &7{ban.id}
  &e
  &aYou can make a unban request at &eforum.example.net.'
  dkbans.punish.message.ban.temporary: '&e&lexample.net
  &e
  &cYou are &e&l{ban.current.durationFormatted} &cbanned from this network
  &3Reason&8: &4&l{ban.current.reason}
  &3BanID&8: &7{ban.id}
  &e
  &3Remaining time&8: &e{ban.current.remainingFormatted}
  &e
  &aYou can make a unban request at &eforum.example.net'

  dkbans.command.report.login.already: '${dkbans.prefix.report} &cYou are already logged in'
  dkbans.command.report.login.success: '${dkbans.prefix.report} &aYou are now logged in'
  dkbans.command.report.logout.already: '${dkbans.prefix.report} &cYou are already logged out'
  dkbans.command.report.logout.success: '${dkbans.prefix.report} &aYou are now logged out'
  dkbans.command.report.toggle.login: '${dkbans.prefix.report} &cYou are already logged in'
  dkbans.command.report.toggle.logout: '${dkbans.prefix.report} &aYou are now logged out'
  dkbans.command.report.template.notExist: '${dkbans.prefix.report} &cThe report template &e{name} &cdoes not exist'
  dkbans.command.report.already.reported: '${dkbans.prefix.report} &cYou have already &e{player.name} &creported'
  dkbans.command.report.reported: '${dkbans.prefix.report} &aYou have already reported &e{player.name} &afor &e{reason}'
  dkbans.command.report.noReason: '${dkbans.prefix.report} &cPlease provide a report reason'
  dkbans.command.report.listTemplates: '${dkbans.prefix.report} &6Available report templates
  @for("template" in {templates}, ${dkbans.command.report.listTemplates.loop},"\n")'
  dkbans.command.report.listTemplates.loop: '&8» &e{template.displayName}'
  dkbans.command.report.take.usage: '${dkbans.prefix.report} &cUse /report take <name>'
  dkbans.report.notFound: '${dkbans.prefix.report} &cA report for &e{player.name} &cwas not found'
  dkbans.command.report.take: '${dkbans.prefix.report} &aYou have took the report of &e{target.name}'
  dkbans.command.report.take.already: '${dkbans.prefix.report} &aThe report of &e{target.name} has been already taken'
  dkbans.command.report.accept.usage: '${dkbans.prefix.report} &cUse /report accept <name>'
  dkbans.command.report.accept.notWatching: '${dkbans.prefix.report} &cYou are not watching this player'